name: autosync
on:
  push:
    paths:
      - '.github/workflows/autosync.yml'
      - './packages.sh'
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
        
env:
  TZ: Asia/Shanghai

jobs:
  autosync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true

      - name: Resync Code
        run: |
          chmod +x packages.sh
          ./packages.sh
      
      - name: Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 添加认证信息到远程URL
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          
          Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
          git add .
          git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
          for pkg in $(git diff-tree --no-commit-id --name-only HEAD | grep -v "naiveproxy"); do
            if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
              sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count main $pkg)/" $pkg/Makefile || true
            fi
          done
          git reset --soft HEAD^
          git add .
          git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
          git push origin HEAD:main -f

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 3
          token: ${{ secrets.GH_TOKEN }}
